### ISSUE TITLE
Aamp not converting some baiprog from yml to aamp correctly.

### ISSUE THREAD

**Issue by ArcAngelofJustice** [leoetlino/aamp#7]
So with some actors, it seems that if aamp is used to save a baiprog file it will change some values to a very high number. This happens consistently. A good example is Enemy_Ganon.baiprog, if you use aamp to convert it to yml, then back to baiprog, one of the ChildIdx listed under AI_21 will go from 64 to a 10 digit number. This also happens with AI_38, and similar occurances happen to Enemy_Siteboss_Lsword_Castle and Enemy_Siteboss_Sword_Castle.

I suspect this is a result of some Japanese Kanji characters not playing nice with aamp/yml.

**Comment by leoetlino** [comment]
Thanks for the bug report. This should be fixed in the latest release (1.4.1).
