### ISSUE TITLE
aamp_to_yml and yml_to_aamp usage

### ISSUE THREAD

**Issue by zardini123** [leoetlino/aamp#9]
How would one be able to convert an aamp file to a yml _file_, edit the file in ones favorite text editor, and then reconvert it to aamp?  I see aamp_to_yml spits the yml out to the console.  Do I need to pipe this console output to a file, and then when ready have this file as the argument to yml_to_aamp?

Thanks!

**Comment by leoetlino** [comment]
Yeah. It's the same as for [byml-v2](https://github.com/zeldamods/byml-v2).
